DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS contents CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS verification_token CASCADE;
